
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from webdriver_manager.chrome import ChromeDriverManager
from time import sleep
from selenium.webdriver.support import expected_conditions


class TestTestrenault():
  def setup_method(self, method):
    self.driver = webdriver.Chrome(ChromeDriverManager().install())
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testrenault(self):
    self.driver.get("https://www.renault.com.tr/")
    self.driver.set_window_size(1936, 1066)
    self.driver.execute_script("window.scrollTo(0,668)")
    sleep(2)
    self.driver.find_element(By.LINK_TEXT, "tüm araçlar").click()
    self.driver.execute_script("window.scrollTo(0,2200)")
    self.driver.execute_script("window.scrollTo(0,376)")
    sleep(2)
    # WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.XPATH, "*//div[@id='tab-0']/div/div[4]/div[5]/button/figure/picture/img")))
    self.driver.find_element(By.XPATH, "//div[@id='tab-0']/div/div[4]/div[5]/button/figure/picture/img").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.execute_script("window.scrollTo(0,352)")
    self.driver.execute_script("window.scrollTo(0,415)")
    sleep(2)
    self.driver.find_element(By.LINK_TEXT, "konfigüratör").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".CfgStep:nth-child(3) .CfgStep__title").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    sleep(10)
    #self.driver.find_element(By.CSS_SELECTOR, ".CriteriaGroup__item:nth-child(5) .PictureElement__imgDefault").click()
    self.driver.execute_script("window.scrollTo(0,316)")
    sleep(2)
    #self.driver.find_element(By.CSS_SELECTOR, ".ResponsiveTabs__tab_pos1").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".ResponsiveTabs__tab_pos1")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element)
    sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".ResponsiveTabs__tab_pos2").click()
    sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".CfgStep:nth-child(4) .CfgStep__title").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".CfgStep:nth-child(4) .CfgStep__title")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element)
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.execute_script("window.scrollTo(0,600)")
    sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, "#tab-1 .EquipmentCardItem__addButtonText").click()
    sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, ".CfgStep:nth-child(5) .CfgStep__index").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".CfgStep:nth-child(5) .CfgStep__index")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element)
    self.driver.execute_script("window.scrollTo(0,0)")
    sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, ".CfgNewRecapCtas__link").click()
    self.driver.execute_script("window.scrollTo(0,300)")
    self.driver.execute_script("window.scrollTo(0,0)")
    sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, ".Button_navNext > .Button__content").click()
    self.driver.execute_script("window.scrollTo(0,373)")
    sleep(5)
    self.driver.find_element(By.ID, "annualMileage").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, ".Button_navNext > .Button__content").click()
    self.driver.execute_script("window.scrollTo(0,300)")
    sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, ".Button_navNext").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".Button_navNext")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element)
    element = self.driver.find_element(By.CSS_SELECTOR, ".Button_navNext > .Button__content")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element)
    sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, ".FuelStep__question_active").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, ".Button_navNext > .Button__content").click()
    self.driver.execute_script("window.scrollTo(0,373)")
    sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, ".CheckoutNavigationButtons__wrapper").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".Button_navNext > .Button__content")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, ".Button_navNext > .Button__content").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, ".Button_navNext > .Button__content").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".Button_navNext > .Button__content")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element)
    sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, ".Button_navNext > .Button__content").click()
    sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, ".FuelCarResults__estimatedResultValue").click()
    sleep(5)
    assert self.driver.find_element(By.CSS_SELECTOR, ".FuelCarResults__estimatedResultValue").text == "6,8"